In [1]:
!pip install lightgbm

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lightgbm in /abr/jn_hack13/.local/lib/python3.10/site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from lightgbm) (1.26.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from lightgbm) (1.15.3)

In [2]:
import pandas as pd
import numpy as np
import os
import glob
import random

import warnings
warnings.filterwarnings("ignore")

## Baseline

In [3]:
train = pd.read_csv('./EXAMPLE_DACON/train.csv')

In [4]:
train.tail()

        Day  Hour  Minute  DHI  DNI   WS     RH  T  TARGET
52555  1094    21      30    0    0  2.4  70.70 -4     0.0
52556  1094    22       0    0    0  2.4  66.79 -4     0.0
52557  1094    22      30    0    0  2.2  66.78 -4     0.0
52558  1094    23       0    0    0  2.1  67.72 -4     0.0
52559  1094    23      30    0    0  2.1  67.70 -4     0.0

In [5]:
def preprocess_data(data, is_train=True):
    
    temp = data.copy()
    temp = temp[['Hour', 'TARGET', 'DHI', 'DNI', 'WS', 'RH', 'T']]

    if is_train==True:          
    
        temp['Target1'] = temp['TARGET'].shift(-48).fillna(method='ffill')
        temp['Target2'] = temp['TARGET'].shift(-48*2).fillna(method='ffill')
        temp = temp.dropna()
        
        return temp.iloc[:-96]

    elif is_train==False:
        
        temp = temp[['Hour', 'TARGET', 'DHI', 'DNI', 'WS', 'RH', 'T']]
                              
        return temp.iloc[-48:, :]


df_train = preprocess_data(train)
df_train.iloc[:48]

    Hour     TARGET  DHI  DNI   WS     RH   T    Target1    Target2
0      0   0.000000    0    0  1.5  69.08 -12   0.000000   0.000000
1      0   0.000000    0    0  1.5  69.06 -12   0.000000   0.000000
2      1   0.000000    0    0  1.6  71.78 -12   0.000000   0.000000
3      1   0.000000    0    0  1.6  71.75 -12   0.000000   0.000000
4      2   0.000000    0    0  1.6  75.20 -12   0.000000   0.000000
5      2   0.000000    0    0  1.5  69.29 -11   0.000000   0.000000
6      3   0.000000    0    0  1.5  72.56 -11   0.000000   0.000000
7      3   0.000000    0    0  1.4  72.55 -11   0.000000   0.000000
8      4   0.000000    0    0  1.3  74.62 -11   0.000000   0.000000
9      4   0.000000    0    0  1.3  74.61 -11   0.000000   0.000000
10     5   0.000000    0    0  1.3  73.74 -11   0.000000   0.000000
11     5   0.000000    0    0  1.3  73.73 -11   0.000000   0.000000
12     6   0.000000    0    0  1.4  72.22 -12   0.000000   0.000000
13     6   0.000000    0    0  1.4  72.22 -12   0.000000   0.000000
14     7   0.000000    0    0  1.4  70.27 -12   0.000000   0.000000
15     7   0.000000    0    0  1.6  64.83 -10   0.000000   0.000000
16     8   7.039287   29  494  1.8  65.45  -9   7.133144   0.750808
17     8   5.912871   61    7  1.9  55.90  -7  14.922796   1.689299
18     9  22.337268   58  743  2.1  57.39  -6  22.806037   5.161690
19     9  29.469529   67  811  1.9  53.15  -4   2.158549   4.973992
20    10  25.339762  138  368  1.8  55.99  -3  36.225679  16.517408
21    10  25.152060  178  224  1.9  55.97  -3  41.386914   9.760179
22    11  28.718397  193  261  2.0  58.43  -3  45.140829   7.601678
23    11  33.129393  189  364  2.3  58.41  -3  47.580874  10.980202
24    12  19.427151  190   37  2.6  59.19  -3  48.612666  17.361857
25    12  25.715166  213  133  2.9  59.18  -3  48.143432   4.880090
26    13  24.589225  211  114  3.2  63.27  -4  46.172141  13.326545
27    13  21.304405  185  101  3.1  63.27  -4  42.794162   9.478740
28    14  11.731500  124    2  3.0  62.84  -4  38.195666   4.504797
29    14  14.734764  135   69  2.7  62.85  -4  32.283670   2.627827
30    15   5.818888   62    0  2.5  68.55  -5  25.432775  14.265504
31    15   7.602096   73   39  2.2  68.55  -5  17.737444  16.611987
32    16   4.035725   41   11  2.0  70.27  -6   9.854244   9.010089
33    16   0.938541   10    0  2.0  70.28  -6   2.627827   2.440259
34    17   0.000000    0    0  2.0  71.33  -7   0.000000   0.000000
35    17   0.000000    0    0  2.0  71.35  -7   0.000000   0.000000
36    18   0.000000    0    0  2.1  76.43  -8   0.000000   0.000000
37    18   0.000000    0    0  2.2  76.44  -8   0.000000   0.000000
38    19   0.000000    0    0  2.3  76.72  -8   0.000000   0.000000
39    19   0.000000    0    0  2.2  76.72  -8   0.000000   0.000000
40    20   0.000000    0    0  2.2  77.51  -8   0.000000   0.000000
41    20   0.000000    0    0  2.0  77.51  -8   0.000000   0.000000
42    21   0.000000    0    0  1.9  83.46  -9   0.000000   0.000000
43    21   0.000000    0    0  1.8  83.46  -9   0.000000   0.000000
44    22   0.000000    0    0  1.8  83.36  -9   0.000000   0.000000
45    22   0.000000    0    0  1.7  83.36  -9   0.000000   0.000000
46    23   0.000000    0    0  1.7  90.86 -10   0.000000   0.000000
47    23   0.000000    0    0  1.6  90.85 -10   0.000000   0.000000

In [6]:
train.iloc[48:96]

    Day  Hour  Minute  DHI  DNI   WS     RH   T     TARGET
48    1     0       0    0    0  1.6  90.66 -10   0.000000
49    1     0      30    0    0  1.6  90.68 -10   0.000000
50    1     1       0    0    0  1.6  88.11 -11   0.000000
51    1     1      30    0    0  1.6  88.11 -11   0.000000
52    1     2       0    0    0  1.6  90.85 -11   0.000000
53    1     2      30    0    0  1.6  90.84 -11   0.000000
54    1     3       0    0    0  1.7  93.78 -12   0.000000
55    1     3      30    0    0  1.7  93.77 -12   0.000000
56    1     4       0    0    0  1.7  90.46 -12   0.000000
57    1     4      30    0    0  1.6  90.46 -12   0.000000
58    1     5       0    0    0  1.6  87.34 -12   0.000000
59    1     5      30    0    0  1.6  87.34 -12   0.000000
60    1     6       0    0    0  1.7  84.96 -12   0.000000
61    1     6      30    0    0  1.7  84.96 -12   0.000000
62    1     7       0    0    0  1.8  83.20 -12   0.000000
63    1     7      30    0    0  2.0  70.75 -10   0.000000
64    1     8       0   27  519  2.3  73.26  -9   7.133144
65    1     8      30   41  690  2.8  57.87  -6  14.922796
66    1     9       0   49  799  3.3  66.23  -4  22.806037
67    1     9      30   23    0  3.0  56.92  -2   2.158549
68    1    10       0   60  910  2.7  57.91  -1  36.225679
69    1    10      30   64  938  2.4  53.78   0  41.386914
70    1    11       0   66  961  2.1  59.87   0  45.140829
71    1    11      30   67  972  1.9  55.63   0  47.580874
72    1    12       0   67  980  1.7  58.88   1  48.612666
73    1    12      30   66  978  1.5  58.86   1  48.143432
74    1    13       0   64  972  1.4  60.68   2  46.172141
75    1    13      30   62  958  1.2  60.66   1  42.794162
76    1    14       0   57  936  1.2  61.34   1  38.195666
77    1    14      30   53  902  0.9  61.33   0  32.283670
78    1    15       0   46  852  0.6  72.29   0  25.432775
79    1    15      30   39  772  0.5  77.79  -1  17.737444
80    1    16       0   28  641  0.5  68.91  -2   9.854244
81    1    16      30   14  389  0.4  74.29  -3   2.627827
82    1    17       0    0    0  0.4  67.81  -4   0.000000
83    1    17      30    0    0  0.8  73.20  -5   0.000000
84    1    18       0    0    0  1.3  73.62  -6   0.000000
85    1    18      30    0    0  1.5  73.60  -6   0.000000
86    1    19       0    0    0  1.8  74.97  -7   0.000000
87    1    19      30    0    0  2.0  74.95  -7   0.000000
88    1    20       0    0    0  2.2  71.27  -8   0.000000
89    1    20      30    0    0  2.2  71.26  -8   0.000000
90    1    21       0    0    0  2.2  74.50  -8   0.000000
91    1    21      30    0    0  2.2  74.50  -8   0.000000
92    1    22       0    0    0  2.2  72.83  -8   0.000000
93    1    22      30    0    0  2.2  72.82  -8   0.000000
94    1    23       0    0    0  2.2  72.51  -8   0.000000
95    1    23      30    0    0  2.2  72.49  -8   0.000000

In [7]:
train.iloc[48+48:96+48]

     Day  Hour  Minute  DHI  DNI   WS     RH   T     TARGET
96     2     0       0    0    0  2.2  73.80  -8   0.000000
97     2     0      30    0    0  2.1  68.20  -8   0.000000
98     2     1       0    0    0  2.1  69.06  -8   0.000000
99     2     1      30    0    0  2.1  69.04  -8   0.000000
100    2     2       0    0    0  2.2  69.38  -8   0.000000
101    2     2      30    0    0  2.2  69.36  -7   0.000000
102    2     3       0    0    0  2.2  70.03  -7   0.000000
103    2     3      30    0    0  2.2  70.02  -7   0.000000
104    2     4       0    0    0  2.3  72.18  -7   0.000000
105    2     4      30    0    0  2.4  66.78  -7   0.000000
106    2     5       0    0    0  2.5  68.32  -7   0.000000
107    2     5      30    0    0  2.5  68.32  -7   0.000000
108    2     6       0    0    0  2.6  69.68  -7   0.000000
109    2     6      30    0    0  2.6  69.69  -6   0.000000
110    2     7       0    0    0  2.6  74.08  -6   0.000000
111    2     7      30    0    0  2.4  63.54  -4   0.000000
112    2     8       0    8    0  2.2  72.05  -3   0.750808
113    2     8      30   18    0  2.0  66.85  -2   1.689299
114    2     9       0   55    0  1.8  72.81  -1   5.161690
115    2     9      30   53    0  2.0  67.63  -1   4.973992
116    2    10       0  153   65  2.2  72.03  -1  16.517408
117    2    10      30  104    0  2.6  72.02   0   9.760179
118    2    11       0   81    0  3.1  75.29   0   7.601678
119    2    11      30  117    0  3.5  75.28   0  10.980202
120    2    12       0  176   20  3.9  75.99   0  17.361857
121    2    12      30   52    0  4.3  76.01   0   4.880090
122    2    13       0  141    3  4.7  79.12  -1  13.326545
123    2    13      30  101    0  5.0  79.17  -1   9.478740
124    2    14       0   48    0  5.3  78.49  -2   4.504797
125    2    14      30   28    0  5.1  84.71  -3   2.627827
126    2    15       0  110  157  5.1  80.48  -4  14.265504
127    2    15      30   71  535  4.4  86.96  -5  16.611987
128    2    16       0   47  403  3.7  79.93  -7   9.010089
129    2    16      30   26    0  3.1  86.46  -8   2.440259
130    2    17       0    0    0  2.6  80.46  -9   0.000000
131    2    17      30    0    0  2.3  87.15  -9   0.000000
132    2    18       0    0    0  2.0  85.23 -10   0.000000
133    2    18      30    0    0  1.7  85.26 -10   0.000000
134    2    19       0    0    0  1.5  85.29 -11   0.000000
135    2    19      30    0    0  1.2  85.30 -11   0.000000
136    2    20       0    0    0  0.9  86.81 -12   0.000000
137    2    20      30    0    0  0.7  86.81 -12   0.000000
138    2    21       0    0    0  0.5  82.90 -12   0.000000
139    2    21      30    0    0  0.4  82.89 -12   0.000000
140    2    22       0    0    0  0.4  79.09 -13   0.000000
141    2    22      30    0    0  0.7  79.08 -13   0.000000
142    2    23       0    0    0  1.1  81.09 -13   0.000000
143    2    23      30    0    0  1.4  81.08 -13   0.000000

In [8]:
df_train.tail()

       Hour  TARGET  DHI  DNI   WS     RH  T  Target1  Target2
52459    21     0.0    0    0  3.5  55.97 -1      0.0      0.0
52460    22     0.0    0    0  3.9  54.23 -2      0.0      0.0
52461    22     0.0    0    0  4.1  54.21 -2      0.0      0.0
52462    23     0.0    0    0  4.3  56.46 -2      0.0      0.0
52463    23     0.0    0    0  4.1  56.44 -2      0.0      0.0

In [10]:
df_test = []

for i in range(41):
    file_path = './EXAMPLE_DACON/test/' + str(i) + '.csv'
    temp = pd.read_csv(file_path)
    temp = preprocess_data(temp, is_train=False)
    df_test.append(temp)

X_test = pd.concat(df_test)
X_test.shape

(1968, 7)

In [ ]:
X_test.head(48)

In [ ]:
df_train.head()

In [ ]:
df_train.iloc[-48:]

In [ ]:
from sklearn.model_selection import train_test_split
X_train_1, X_valid_1, Y_train_1, Y_valid_1 = train_test_split(df_train.iloc[:, :-2], df_train.iloc[:, -2], test_size=0.3, random_state=0)
X_train_2, X_valid_2, Y_train_2, Y_valid_2 = train_test_split(df_train.iloc[:, :-2], df_train.iloc[:, -1], test_size=0.3, random_state=0)

In [ ]:
X_train_1.head()

In [ ]:
X_test.head()

In [ ]:
X_test.head()

In [ ]:
quantiles = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

In [ ]:
from lightgbm import LGBMRegressor

# Get the model and the predictions in (a) - (b)
def LGBM(q, X_train, Y_train, X_valid, Y_valid, X_test):
    
    # (a) Modeling  
    model = LGBMRegressor(objective='quantile', alpha=q,
                         n_estimators=10000, bagging_fraction=0.7, learning_rate=0.027, subsample=0.7, force_row_wise=True )                
                         
                         
    model.fit(X_train, Y_train, eval_metric = ['quantile'], 
          eval_set=[(X_valid, Y_valid)])

    # (b) Predictions
    pred = pd.Series(model.predict(X_test).round(2))
    return pred, model

In [ ]:
# Target 예측

def train_data(X_train, Y_train, X_valid, Y_valid, X_test):

    LGBM_models=[]
    LGBM_actual_pred = pd.DataFrame()

    for q in quantiles:
        print(q)
        pred , model = LGBM(q, X_train, Y_train, X_valid, Y_valid, X_test)
        LGBM_models.append(model)
        LGBM_actual_pred = pd.concat([LGBM_actual_pred,pred],axis=1)

    LGBM_actual_pred.columns=quantiles
    
    return LGBM_models, LGBM_actual_pred

In [ ]:
# Target1
models_1, results_1 = train_data(X_train_1, Y_train_1, X_valid_1, Y_valid_1, X_test)
results_1.sort_index()[:48]

In [ ]:
# Target2
models_2, results_2 = train_data(X_train_2, Y_train_2, X_valid_2, Y_valid_2, X_test)
results_2.sort_index()[:48]

In [ ]:
results_1.sort_index().iloc[:48]

In [ ]:
## 모델 검증 코드 ( 중복 사용 / 예시로 참고 )

In [ ]:
results_1

In [ ]:
models = [*models_1, *models_2]
model_quantiles = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
X_test = pd.concat([X_valid_1, X_valid_2])
Y_test = pd.concat([Y_valid_1, Y_valid_2])

results = []

for model, quantile in list(zip(models, model_quantiles)):
    pred = model.predict(X_test)
    print (quantile, len(pred), len(Y_test))
    results.

In [ ]:
from sklearn.metrics import mean_squared_error, mean_pinball_loss
import numpy as np
import pandas as pd

def _predict_best(model, X):
    num_iter = getattr(model, "best_iteration_", None)
    return model.predict(X, num_iteration=num_iter)

def evaluate_models(models, X_valid, Y_valid, target_name):
    rows = []
    # 예측 샘플 저장용
    sample_out = []

    for i, model in enumerate(models):
        q = model.get_params().get('alpha', None)  # 분위수 복원
        y_pred = _predict_best(model, X_valid)     # 반올림 금지(정밀도 유지)
        rmse = np.sqrt(mean_squared_error(Y_valid, y_pred))
        qloss = mean_pinball_loss(Y_valid, y_pred, alpha=q) if q is not None else np.nan

        rows.append({
            "target": target_name,
            "quantile": q,
            "best_iter": getattr(model, "best_iteration_", None),
            "valid_rmse": rmse,
            "valid_quantile_loss": qloss
        })

        # 예측 샘플 (상위 3개)
        sample_out.append((target_name, q, y_pred[:3].tolist()))

    metrics_df = pd.DataFrame(rows).sort_values(["target", "quantile"]).reset_index(drop=True)

    # 마지막에 모델 예측 결과 샘플 출력
    print(f"=== [{target_name}] prediction samples (first 3) ===")
    for t, q, arr in sample_out:
        print(f"target={t}, q={q} -> {arr}")

    return metrics_df

# ───────────── 평가 실행 (타겟별로 분리 평가) ─────────────
metrics_1 = evaluate_models(models_1, X_valid_1, Y_valid_1, target_name="target1")
metrics_2 = evaluate_models(models_2, X_valid_2, Y_valid_2, target_name="target2")

# 합쳐서 보기
metrics_all = pd.concat([metrics_1, metrics_2], ignore_index=True)
print("\n=== Validation Metrics (by target & quantile) ===")
print(metrics_all)

# (선택) 정렬된 표 형태로 상위 일부 확인
display(metrics_all.sort_values(["target","quantile"]).head(20))

In [ ]:
import numpy as np
import pandas as pd

def add_composite_score(metrics_all: pd.DataFrame, 
                        w_rmse: float = 0.5, 
                        w_qloss: float = 0.5,
                        groupby_col: str = "target"):
    """
    metrics_all: columns = ['target','quantile','valid_rmse','valid_quantile_loss', ...]
    반환: score, score_0_100 컬럼 추가된 DataFrame
    """
    df = metrics_all.copy()

    # 1) 타깃별 스케일 산출(중앙값; 0/NaN 방지)
    rmse_med = df.groupby(groupby_col)['valid_rmse'].transform('median').replace({0: np.nan})
    ql_med   = df.groupby(groupby_col)['valid_quantile_loss'].transform('median').replace({0: np.nan})

    # 2) 정규화 (값이 클수록 나쁨 → 1 이상이면 중앙값보다 나쁨)
    df['RMSE_norm'] = df['valid_rmse'] / rmse_med
    df['QLoss_norm'] = df['valid_quantile_loss'] / ql_med

    # 결측/무한치 방어
    for col in ['RMSE_norm', 'QLoss_norm']:
        df[col] = df[col].replace([np.inf, -np.inf], np.nan)
    df[['RMSE_norm','QLoss_norm']] = df[['RMSE_norm','QLoss_norm']].fillna(df[['RMSE_norm','QLoss_norm']].median())

    # 3) 가중 합 → 역수(높을수록 좋은 점수)
    denom = (w_rmse * df['RMSE_norm'] + w_qloss * df['QLoss_norm'])
    # 아주 드문 0 방지
    denom = denom.replace(0, denom[denom != 0].min())
    df['score'] = 1.0 / denom

    # 4) 보기 좋은 0~100 스케일(타깃별 Min-Max)
    def _mm(x):
        x_min, x_max = x.min(), x.max()
        return 100 * (x - x_min) / (x_max - x_min) if x_max > x_min else 100.0
    df['score_0_100'] = df.groupby(groupby_col)['score'].transform(_mm).round(2)

    # 5) 정렬 예시
    df = df.sort_values([groupby_col, 'score'], ascending=[True, False]).reset_index(drop=True)
    return df

# 사용 예시
metrics_all = add_composite_score(metrics_all, w_rmse=0.5, w_qloss=0.5)
score = np.mean(metrics_all['score'])

In [ ]:
print(f"SCORE: {score}")